const COP_CURRENCY = 'cop';
const COP_MINOR_UNIT_MULTIPLIER = 100;
const MINIMUM_QUOTE_TOTAL_COP = 10000;
const MEDIDA_MAXIMA_CM = 250;

const TIPOS_CITA_VALIDOS = ['consulta', 'medidas', 'otro'];
const MINUTO_INICIO_JORNADA = 8 * 60;
const MINUTO_FIN_JORNADA = 17 * 60;

module.exports = {
  COP_CURRENCY,
  COP_MINOR_UNIT_MULTIPLIER,
  MINIMUM_QUOTE_TOTAL_COP,
  MEDIDA_MAXIMA_CM,
  TIPOS_CITA_VALIDOS,
  MINUTO_INICIO_JORNADA,
  MINUTO_FIN_JORNADA,
};
